// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful API response",
            "schema": {
              "$ref": "#/definitions/IProductStock[]"
            }
          },
          "500": {
            "description": "Internal server error!"
          }
        }
      },
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Product Created",
            "schema": {
              "$ref": "#/definitions/IProductStock"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal server error!"
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful API response",
            "schema": {
              "$ref": "#/definitions/IProduct"
            }
          },
          "404": {
            "description": "Product not found!"
          },
          "500": {
            "description": "Internal server error!"
          }
        }
      }
    }
  },
  "definitions": {
    "IProduct": {
      "properties": {
        "title": {
          "title": "IProduct.title",
          "type": "string"
        },
        "description": {
          "title": "IProduct.description",
          "type": "string"
        },
        "id": {
          "title": "IProduct.id",
          "type": "string"
        },
        "price": {
          "title": "IProduct.price",
          "type": "number"
        }
      },
      "required": [
        "title",
        "description",
        "id",
        "price"
      ],
      "additionalProperties": false,
      "title": "IProduct",
      "type": "object"
    },
    "IStock": {
      "properties": {
        "product_id": {
          "title": "IStock.product_id",
          "type": "string"
        },
        "count": {
          "title": "IStock.count",
          "type": "number"
        }
      },
      "required": [
        "product_id",
        "count"
      ],
      "additionalProperties": false,
      "title": "IStock",
      "type": "object"
    },
    "IProductStock": {
      "properties": {
        "count": {
          "title": "IProductStock.count",
          "type": "number"
        }
      },
      "required": [
        "count"
      ],
      "additionalProperties": false,
      "title": "IProductStock",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "host": "50tdgqcex4.execute-api.us-east-1.amazonaws.com/dev"
};