// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful API response",
            "schema": {
              "$ref": "#/definitions/IProduct"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successful API response",
            "schema": {
              "$ref": "#/definitions/IProduct"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "IProduct": {
      "properties": {
        "count": {
          "title": "IProduct.count",
          "type": "number"
        },
        "title": {
          "title": "IProduct.title",
          "type": "string"
        },
        "description": {
          "title": "IProduct.description",
          "type": "string"
        },
        "id": {
          "title": "IProduct.id",
          "type": "string"
        },
        "price": {
          "title": "IProduct.price",
          "type": "number"
        }
      },
      "required": [
        "count",
        "title",
        "description",
        "id",
        "price"
      ],
      "additionalProperties": false,
      "title": "IProduct",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};