// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful API response",
            "schema": {
              "$ref": "#/definitions/IProduct"
            }
          },
          "500": {
            "description": "Internal server error!"
          }
        }
      },
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Product Created",
            "schema": {
              "$ref": "#/definitions/IProduct"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal server error!"
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successful API response",
            "schema": {
              "$ref": "#/definitions/IProduct"
            }
          },
          "404": {
            "description": "Product not found!"
          },
          "500": {
            "description": "Internal server error!"
          }
        }
      }
    }
  },
  "definitions": {
    "IProduct": {
      "properties": {
        "count": {
          "title": "IProduct.count",
          "type": "number"
        },
        "title": {
          "title": "IProduct.title",
          "type": "string"
        },
        "description": {
          "title": "IProduct.description",
          "type": "string"
        },
        "id": {
          "title": "IProduct.id",
          "type": "string"
        },
        "price": {
          "title": "IProduct.price",
          "type": "number"
        }
      },
      "required": [
        "count",
        "title",
        "description",
        "id",
        "price"
      ],
      "additionalProperties": false,
      "title": "IProduct",
      "type": "object"
    },
    "IProductDB": {
      "properties": {
        "TableName": {
          "title": "IProductDB.TableName",
          "type": "string"
        },
        "Item": {
          "properties": {
            "id": {
              "properties": {
                "S": {
                  "title": "IProductDB.Item.id.S",
                  "type": "string"
                }
              },
              "required": [
                "S"
              ],
              "additionalProperties": false,
              "title": "IProductDB.Item.id",
              "type": "object"
            },
            "title": {
              "properties": {
                "S": {
                  "title": "IProductDB.Item.title.S",
                  "type": "string"
                }
              },
              "required": [
                "S"
              ],
              "additionalProperties": false,
              "title": "IProductDB.Item.title",
              "type": "object"
            },
            "price": {
              "properties": {
                "N": {
                  "title": "IProductDB.Item.price.N",
                  "type": "number"
                }
              },
              "required": [
                "N"
              ],
              "additionalProperties": false,
              "title": "IProductDB.Item.price",
              "type": "object"
            },
            "description": {
              "properties": {
                "S": {
                  "title": "IProductDB.Item.description.S",
                  "type": "string"
                }
              },
              "required": [
                "S"
              ],
              "additionalProperties": false,
              "title": "IProductDB.Item.description",
              "type": "object"
            }
          },
          "required": [
            "id",
            "title",
            "price",
            "description"
          ],
          "additionalProperties": false,
          "title": "IProductDB.Item",
          "type": "object"
        }
      },
      "required": [
        "TableName",
        "Item"
      ],
      "additionalProperties": false,
      "title": "IProductDB",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "host": "50tdgqcex4.execute-api.us-east-1.amazonaws.com/dev"
};